--USE MASTER;

/*CREATE DATABASE PROPINA_CARRASCO;
GO*/

USE PROPINA_CARRASCO;
GO

DROP TABLE dbo.PLANILLAEMPLEADO;
DROP TABLE dbo.PLANILLA;
DROP TABLE dbo.ADMINISTRADOR;
DROP TABLE dbo.EMPLEADO;
DROP TABLE dbo.USUARIO;
DROP TABLE dbo.CARGO;
DROP TABLE dbo.REPARTODIARIO;
DROP TABLE dbo.REPARTO;

CREATE TABLE dbo.CARGO
(
	Id	INT  NOT NULL IDENTITY(1,1),
	Nombre NVARCHAR(30) NOT NULL,	

	CONSTRAINT PK_CARGO PRIMARY KEY(Id),
);
GO

CREATE TABLE dbo.USUARIO
(
	Id	INT  NOT NULL IDENTITY(1,1),	
	Nombre NVARCHAR(30) NOT NULL,
	Apellido NVARCHAR(30) NOT NULL,
	NombreUsuario NVARCHAR(50) NOT NULL,
	Contrasenia NVARCHAR(MAX) NOT NULL,
	Habilitado BIT NOT NULL,
	Tipo NVARCHAR(20) NOT NULL,
	
	Email NVARCHAR(50),
	Telefono NVARCHAR(20),
	Direccion NVARCHAR (100),

	CONSTRAINT PK_USUARIO PRIMARY KEY(Id),
	CONSTRAINT UK_NombreUsuario_USUARIO UNIQUE(NombreUsuario),
	CONSTRAINT CK_COL_Tipo_InValores_TAB_USUARIO CHECK (Tipo in('EMPLEADO', 'ADMINISTRADOR'))
);
GO

CREATE TABLE dbo.EMPLEADO
(
	EmpleadoId INT  NOT NULL,	
	NumeroEmpleado INT NOT NULL,
	CargoId INT NOT NULL,

	CONSTRAINT PK_EMPLEADO PRIMARY KEY(EmpleadoId),
	CONSTRAINT UK_NumeroEmpleado_EMPLEADO UNIQUE(NumeroEmpleado),
	CONSTRAINT FK_UsuarioId_EMPLEADO FOREIGN KEY (EmpleadoId) REFERENCES dbo.USUARIO (Id),
	CONSTRAINT FK_CargoId_EMPLEADO FOREIGN KEY (CargoId) REFERENCES dbo.CARGO (Id)
);
GO

CREATE TABLE dbo.ADMINISTRADOR
(
	UsuarioId INT  NOT NULL,

	CONSTRAINT PK_ADMINISTRADOR PRIMARY KEY(UsuarioId),
	CONSTRAINT FK_UsuarioId_ADMINISTRADOR FOREIGN KEY (UsuarioId) REFERENCES dbo.USUARIO (Id)
);
GO

CREATE TABLE dbo.PLANILLA
(
	Id	INT  NOT NULL IDENTITY(1,1),
	Texto NVARCHAR(500) NOT NULL,
	FechaAlta DATETIME NOT NULL,
	IdEmpleado INT NOT NULL,
	Habilitada BIT NOT NULL,
	Eliminado BIT NOT NULL,

	CONSTRAINT PK_PLANILLA PRIMARY KEY(Id),
	CONSTRAINT FK_EmpleadoId_PLANILLA FOREIGN KEY (IdEmpleado) REFERENCES dbo.EMPLEADO (EmpleadoId)
);
GO

CREATE TABLE dbo.PLANILLAEMPLEADO
(
	EmpleadoId INT  NOT NULL,
	PlanillaId INT  NOT NULL,

	CONSTRAINT PK_PLANILLAEMPLEADO PRIMARY KEY(EmpleadoId, PlanillaId),
	CONSTRAINT FK_EmpleadoId_PLANILLAEMPLEADO FOREIGN KEY (EmpleadoId) REFERENCES dbo.EMPLEADO (EmpleadoId),
	CONSTRAINT FK_PlanillaId_PLANILLAEMPLEADO FOREIGN KEY (PlanillaId) REFERENCES dbo.PLANILLA (Id)
);
GO

CREATE TABLE dbo.REPARTO
(
	Id	INT  NOT NULL IDENTITY(1,1),
	MontoTotalPesos NUMERIC(12,2) NOT NULL,
	MontoTotalDolares NUMERIC(12,2) NOT NULL,
	Fecha DATETIME NOT NULL,
	Activo BIT NOT NULL,

	CONSTRAINT PK_REPARTO PRIMARY KEY(Id)
);
GO

CREATE TABLE dbo.REPARTODIARIO
(
	Id INT NOT NULL IDENTITY(1,1),
	IdReparto INT  NOT NULL,
	Fecha DATETIME NOT NULL,
	MontoPesosMesas NUMERIC(12,2) NOT NULL,
	MontoDolaresMesas NUMERIC(12,2) NOT NULL,
	MontoPesosOtros NUMERIC(12,2) NOT NULL,
	MontoDolaresOtros NUMERIC(12,2) NOT NULL,
	
	CONSTRAINT PK_REPARTODIARIO PRIMARY KEY(Id),
	CONSTRAINT FK_IdReparto_REPARTODIARIO FOREIGN KEY (IdReparto) REFERENCES dbo.REPARTO (Id)
);
GO

INSERT INTO CARGO VALUES
('CROUPIER'),
('SUPERVIDOR_MESAS'),
('CAJERO'),
('SUPERVISOR_CAJAS'),
('MARKETING'),
('SLOTS'),
('TECNICOS_SLOTS'),
('SOFTCOUNT'),
('SERVICIOS_GENERALES'),
('MANTENIMIENTO');

INSERT INTO dbo.USUARIO VALUES
/*1 - Admin*/('Admin1', 'Admin1', 'Admin1','123456789', 1, 'ADMINISTRADOR', 'Admin1@mailinator.com', '099999999', 'Admin dir'),
/*2 - Admin*/('Admin2', 'Admin2', 'Admin2','123456789', 1, 'ADMINISTRADOR', 'Admin2@mailinator.com', '099999999', 'Admin dir'),

/*3 - Empleado*/('Empleado1', 'Empleado1', 'Empleado1','123456789', 1, 'EMPLEADO', 'Empleado1@mailinator.com', '099999999', 'Empleado1 dir'),
/*4 - Empleado*/('Empleado2', 'Empleado2', 'Empleado2','123456789', 1, 'EMPLEADO', 'Empleado2@mailinator.com', '099999999', 'Empleado2 dir');

INSERT INTO dbo.ADMINISTRADOR VALUES
(1),
(2);

INSERT INTO dbo.EMPLEADO Values
(3,100,1),
(4,101,5);

INSERT INTO dbo.PLANILLA Values
('Texto 1',getdate(),3,1,0),
('Texto 2',getdate(),4,0,0);

INSERT INTO dbo.PLANILLAEMPLEADO Values
(4,1),
(3,2);

INSERT INTO dbo.REPARTO Values
(800000,30000,'1/22/2018',0),
(900000,20000,'2/22/2018',0),
(950000,28000,'3/22/2018',0);

INSERT INTO dbo.REPARTODIARIO Values
(1,'1/1/2018',30000,2500,0,0),
(1,'1/2/2018',25000,2300,0,0),
(1,'1/3/2018',28000,2100,0,0),
(1,'1/4/2018',32000,2000,0,0),
(1,'1/5/2018',27000,1800,0,0),
(1,'1/6/2018',24000,2150,15000,400);

SELECT * FROM USUARIO;
SELECT * FROM EMPLEADO;
SELECT * FROM ADMINISTRADOR;
SELECT * FROM PLANILLA;
SELECT * FROM PLANILLAEMPLEADO;
SELECT * FROM REPARTO;
SELECT * FROM REPARTODIARIO;



